import { type PokemonVersion } from "~/types";

type BadgeMetadata = {
  iconPathLeader: string;
  iconPathGym: string;
  leaderName: string;
  location: string;
  specialty: string;
  reward: string;
  unlocks: string;
  level: string;
};

type PokemonVersionMetadata = Record<number, BadgeMetadata>;

const red: PokemonVersionMetadata = {
  1: {
    iconPathLeader: "/badges/red/1-leader.png",
    iconPathGym: "/badges/red/1-gym.png",
    location: "Pewter City",
    leaderName: "Brock",
    specialty: "Rock-type",
    reward: "Boulder Badge, TM39 (Rock Tomb)",
    unlocks: "Flash",
    level: "12, 14",
  },
  2: {
    iconPathLeader: "/badges/red/2-leader.png",
    iconPathGym: "/badges/red/2-gym.png",
    location: "Cerulean City",
    leaderName: "Misty",
    specialty: "Water-type",
    reward: "Cascade Badge, TM03 (Water Pulse)",
    unlocks: "Cut",
    level: "18, 21",
  },
  3: {
    iconPathLeader: "/badges/red/3-leader.png",
    iconPathGym: "/badges/red/3-gym.png",
    location: "Vermilion City",
    leaderName: "Lt. Surge",
    specialty: "Electric-type",
    reward: "Thunder Badge, TM34 (Shock Wave)",
    unlocks: "Cut",
    level: "18, 24",
  },
  4: {
    iconPathLeader: "/badges/red/4-leader.png",
    iconPathGym: "/badges/red/4-gym.png",
    location: "Celadon City",
    leaderName: "Erika",
    specialty: "Grass-type",
    reward: "Rainbow Badge, TM19 (Giga Drain)",
    unlocks: "Strength",
    level: "24, 29",
  },
  5: {
    iconPathLeader: "/badges/red/5-leader.png",
    iconPathGym: "/badges/red/5-gym.png",
    location: "Fuchsia City",
    leaderName: "Koga",
    specialty: "Poison-type",
    reward: "Soul Badge, TM06 (Toxic)",
    unlocks: "",
    level: "",
  },
  6: {
    iconPathLeader: "/badges/red/6-leader.png",
    iconPathGym: "/badges/red/6-gym.png",
    location: "Saffron City",
    leaderName: "Sabrina",
    specialty: "Psychic-type",
    reward: "Marsh Badge, TM04 (Calm Mind)",
    unlocks: "Rock Smash",
    level: "37, 43",
  },
  7: {
    iconPathLeader: "/badges/red/7-leader.png",
    iconPathGym: "/badges/red/7-gym.png",
    location: "Cinnabar Island",
    leaderName: "Blaine",
    specialty: "Fire-type",
    reward: "Volcano Badge, TM38 (Fire Blast)",
    unlocks: "Waterfall",
    level: "40, 47",
  },
  8: {
    iconPathLeader: "/badges/red/8-leader.png",
    iconPathGym: "/badges/red/8-gym.png",
    location: "Viridian City",
    leaderName: "Giovanni",
    specialty: "Ground-type",
    reward: "Earth Badge, TM26 (Earthquake)",
    unlocks: "Yes",
    level: "42, 50",
  },
};

const crystal: PokemonVersionMetadata = {
  1: {
    iconPathLeader: "/badges/crystal/1-leader.png",
    iconPathGym: "/badges/crystal/1-gym.png",
    location: "Violet City",
    leaderName: "Falkner",
    specialty: "Flying-type",
    reward: "Zephyr Badge, TM31 (Mud Slap)",
    unlocks: "Flash",
    level: "7, 9",
  },
  2: {
    iconPathLeader: "/badges/crystal/2-leader.png",
    iconPathGym: "/badges/crystal/2-gym.png",
    location: "Azalea Town",
    leaderName: "Bugsy",
    specialty: "Bug-type",
    reward: "Insect Badge, TM49 (Fury Cutter)",
    unlocks: "Cut",
    level: "14, 16",
  },
  3: {
    iconPathLeader: "/badges/crystal/3-leader.png",
    iconPathGym: "/badges/crystal/3-gym.png",
    location: "Goldenrod City",
    leaderName: "Whitney",
    specialty: "Normal-type",
    reward: "Plain Badge, TM45 (Attract)",
    unlocks: "Strengh",
    level: "18, 20",
  },
  4: {
    iconPathLeader: "/badges/crystal/4-leader.png",
    iconPathGym: "/badges/crystal/4-gym.png",
    location: "Ecruteak City",
    leaderName: "Morty",
    specialty: "Ghost-type",
    reward: "Fog Badge, TM30 (Shadow Ball)",
    unlocks: "Surf",
    level: "21, 25",
  },
  5: {
    iconPathLeader: "/badges/crystal/5-leader.png",
    iconPathGym: "/badges/crystal/5-gym.png",
    location: "Cianwood City",
    leaderName: "Chuck",
    specialty: "Fighting-type",
    reward: "Storm Badge, TM01 (Dynamic Punch)",
    unlocks: "Fly",
    level: "27, 30",
  },
  6: {
    iconPathLeader: "/badges/crystal/6-leader.png",
    iconPathGym: "/badges/crystal/6-gym.png",
    location: "Olivine City",
    leaderName: "Jasmine",
    specialty: "Steel-type",
    reward: "Mineral Badge, TM23 (Iron Tail)",
    unlocks: "Boost Defense Stats",
    level: "37, 43",
  },
  7: {
    iconPathLeader: "/badges/crystal/7-leader.png",
    iconPathGym: "/badges/crystal/7-gym.png",
    location: "Mahogany Town",
    leaderName: "Pryce",
    specialty: "Ice-type",
    reward: "Glacier Badge, TM16 (Icy Wind)",
    unlocks: "Waterfall",
    level: "27, 31",
  },
  8: {
    iconPathLeader: "/badges/crystal/8-leader.png",
    iconPathGym: "/badges/crystal/8-gym.png",
    location: "Blackthorn City",
    leaderName: "Clair",
    specialty: "Dragon-type",
    reward: "Rising Badge, TM24 (Dragonbreath)",
    unlocks: "Whirlpool",
    level: "37, 40",
  },
};

const emerald: PokemonVersionMetadata = {
  1: {
    iconPathLeader: "/badges/emerald/1-leader.png",
    iconPathGym: "/badges/emerald/1-gym.png",
    location: "Rustboro City",
    leaderName: "Roxanne",
    specialty: "Rock-type",
    reward: "Stone Badge, TM39 (Rock Tomb)",
    unlocks: "Cut",
    level: "12, 15",
  },
  2: {
    iconPathLeader: "/badges/emerald/2-leader.png",
    iconPathGym: "/badges/emerald/2-gym.png",
    location: "Dewford Town",
    leaderName: "Brawly",
    specialty: "Fighting-type",
    reward: "Knuckle Badge, TM08 (Bulk Up)",
    unlocks: "Flash",
    level: "16, 19",
  },
  3: {
    iconPathLeader: "/badges/emerald/3-leader.png",
    iconPathGym: "/badges/emerald/3-gym.png",
    location: "Mauville City",
    leaderName: "Wattson",
    specialty: "Electric-type",
    reward: "Dynamo Badge, TM72 (Volt Switch)",
    unlocks: "Rock Smash",
    level: "20, 24",
  },
  4: {
    iconPathLeader: "/badges/emerald/4-leader.png",
    iconPathGym: "/badges/emerald/4-gym.png",
    location: "Lavaridge Town",
    leaderName: "Flannery",
    specialty: "Fire-type",
    reward: "Heat Badge, TM50 (Overheat)",
    unlocks: "Strength",
    level: "24, 29",
  },
  5: {
    iconPathLeader: "/badges/emerald/5-leader.png",
    iconPathGym: "/badges/emerald/5-gym.png",
    location: "Petalburg City",
    leaderName: "Norman",
    specialty: "Normal",
    reward: "Balance Badge, TM67 (Retaliate)",
    unlocks: "Surf",
    level: "27, 31",
  },
  6: {
    iconPathLeader: "/badges/emerald/6-leader.png",
    iconPathGym: "/badges/emerald/6-gym.png",
    location: "Fortree City",
    leaderName: "Winona",
    specialty: "Flying",
    reward: "Feather Badge, TM19 (Roost)",
    unlocks: "Fly",
    level: "29, 33",
  },
  7: {
    iconPathLeader: "/badges/emerald/7-leader.png",
    iconPathGym: "/badges/emerald/7-gym.png",
    location: "Mossdeep City",
    leaderName: "Tate & Liza",
    specialty: "Psychic-type",
    reward: "Mind Badge, TM04 (Calm Mind)",
    unlocks: "Dive",
    level: "41, 42",
  },
  8: {
    iconPathLeader: "/badges/emerald/8-leader.png",
    iconPathGym: "/badges/emerald/8-gym.png",
    location: "Sootopolis City",
    leaderName: "Juan",
    specialty: "Water-type",
    reward: "Rain Badge, HM05 (Waterfall)",
    unlocks: "Waterfall",
    level: "41, 46",
  },
};

export const badgeInfo: Record<PokemonVersion, PokemonVersionMetadata> = {
  red,
  crystal,
  emerald,
};

export const badgeInfoGymSize = {
  w: 240,
  h: 160,
};
